[package]
name = "nusamai-shapefile"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
nusamai-geometry = { path = "../nusamai-geometry" }
shapefile = "0.6.0"
